version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo_c
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  auth-service:
    build: ./auth-service
    container_name: authservice_c
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo_c:27017/mydb
  # course-service:
  #   build: ./course-service
  #   container_name: courseservice_c
  #   ports:
  #     - "5002:5002"
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./course-service:/app
  #     - /app/node_modules
  #   environment:
  #     - MONGO_URL=mongodb://mongo_c:27017/mydb
  # payment-service:
  #   build: ./payment-service
  #   container_name: paymentservice_c
  #   ports:
  #     - "5003:5003"
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./payment-service:/app
  #     - /app/node_modules
  #   environment:
  #     - MONGO_URL=mongodb://mongo_c:27017/mydb
  # notfication-service:
  #   build: ./notfication-service
  #   container_name: notificationservice_c
  #   ports:
  #     - "5004:5004"
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./notfication-service:/app
  #     - /app/node_modules
  #   environment:
  #     - MONGO_URL=mongodb://mongo_c:27017/mydb
  # gateway:
  #   build: ./gateway
  #   container_name: gateway_c
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./gateway:/app
  #     - /app/node_modules
  #   environment:
  #     - MONGO_URL=mongodb://mongo_c:27017/mydb
volumes:
  mongo-data:
    